FROM ubuntu:22.04

# Set environment variables
ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC

# Update and install packages
RUN apt-get update && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apt-get install -y tzdata sudo git curl wget figlet lolcat build-essential ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python 3.10, pip, and Python development headers
RUN apt-get update && \
    apt-get install -y python3.10 python3.10-venv python3.10-distutils python3.10-dev && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

# Install GDAL and its dependencies
RUN apt-get update && \
    apt-get install -y libgdal-dev gdal-bin

# Create a symbolic link for lolcat
RUN ln -s /usr/games/lolcat /usr/bin/lolcat

# Set GDAL environment variable (if needed)
ENV GDAL_CONFIG=/usr/bin/gdal-config

# Install Python packages
RUN python3.10 -m pip install \
    birdnetlib==0.13.2 \
    geopandas==0.14.1 \
    geopy==2.4.0 \
    psycopg2-binary==2.9.6 \
    pydub==0.25.1 \
    pyfiglet==1.0.2 \
    python-dotenv==1.0.0 \
    requests==2.31.0 \
    rich==12.5.1 \
    SQLAlchemy==2.0.20 \
    termcolor==2.3.0 \
    tflite-runtime==2.14.0 \
    librosa==0.10.1 \
    resampy==0.4.2 \
    ebird-api==3.0.6 \
    tensorflow 


# Append banner command to .bashrc
RUN echo "clear; figlet 'be/AudioML' | lolcat; echo \"\"" >> /root/.bashrc

WORKDIR /workdir
