FROM biometrioearth/dev:ml_audio_jupyterlab_0.1

# jupyterlab for testing
RUN pip3 install --upgrade "elyra[all]"

EXPOSE 8888

WORKDIR /workdir

CMD ["jupyter-lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
