apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-s3fs-dp-sd-dev
  namespace: kubeflow
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/shared_volume_s3fs_dp_sd_dev"
