name: dev-audio-rstudio-build-and-push
on:
  push:
    branches: [ main ]
    paths:
    - dockerfiles/dev/audio_rstudio/0.1/Dockerfile
    
  workflow_dispatch:

jobs:
  build-and-push-docker-image-dev-audio_rstudio:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/dev/audio_rstudio/0.1/Dockerfile
          platforms: linux/amd64
          push: true
          tags: biometrioearth/dev:audio_rstudio_0.1